// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cds.proto

/*
Package envoy_api_v2 is a generated protocol buffer package.

It is generated from these files:
	api/cds.proto

It has these top-level messages:
	UpstreamBindConfig
	CircuitBreakers
	Cluster
*/
package envoy_api_v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import envoy_api_v21 "api"
import envoy_api_v22 "api"
import _ "api"
import envoy_api_v24 "api"
import envoy_api_v25 "api"
import envoy_api_v26 "api"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf2 "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The service discovery type to use for resolving the cluster.
type Cluster_DiscoveryType int32

const (
	Cluster_STATIC       Cluster_DiscoveryType = 0
	Cluster_STRICT_DNS   Cluster_DiscoveryType = 1
	Cluster_LOGICAL_DNS  Cluster_DiscoveryType = 2
	Cluster_EDS          Cluster_DiscoveryType = 3
	Cluster_ORIGINAL_DST Cluster_DiscoveryType = 4
)

var Cluster_DiscoveryType_name = map[int32]string{
	0: "STATIC",
	1: "STRICT_DNS",
	2: "LOGICAL_DNS",
	3: "EDS",
	4: "ORIGINAL_DST",
}
var Cluster_DiscoveryType_value = map[string]int32{
	"STATIC":       0,
	"STRICT_DNS":   1,
	"LOGICAL_DNS":  2,
	"EDS":          3,
	"ORIGINAL_DST": 4,
}

func (x Cluster_DiscoveryType) String() string {
	return proto.EnumName(Cluster_DiscoveryType_name, int32(x))
}
func (Cluster_DiscoveryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// The load balancer type to use when picking a host in the cluster.
type Cluster_LbPolicy int32

const (
	Cluster_ROUND_ROBIN     Cluster_LbPolicy = 0
	Cluster_LEAST_REQUEST   Cluster_LbPolicy = 1
	Cluster_RING_HASH       Cluster_LbPolicy = 2
	Cluster_RANDOM          Cluster_LbPolicy = 3
	Cluster_ORIGINAL_DST_LB Cluster_LbPolicy = 4
)

var Cluster_LbPolicy_name = map[int32]string{
	0: "ROUND_ROBIN",
	1: "LEAST_REQUEST",
	2: "RING_HASH",
	3: "RANDOM",
	4: "ORIGINAL_DST_LB",
}
var Cluster_LbPolicy_value = map[string]int32{
	"ROUND_ROBIN":     0,
	"LEAST_REQUEST":   1,
	"RING_HASH":       2,
	"RANDOM":          3,
	"ORIGINAL_DST_LB": 4,
}

func (x Cluster_LbPolicy) String() string {
	return proto.EnumName(Cluster_LbPolicy_name, int32(x))
}
func (Cluster_LbPolicy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

// The DNS IP address resolution policy. The options are V4_ONLY, V6_ONLY, and
// AUTO. If this setting is not specified, the value defaults to V4_ONLY. When
// V4_ONLY is selected, the DNS resolver will only perform a lookup for
// addresses in the IPv4 family. If V6_ONLY is selected, the DNS resolver will
// only perform a lookup for addresses in the IPv6 family. If AUTO is
// specified, the DNS resolver will first perform a lookup for addresses in
// the IPv6 family and fallback to a lookup for addresses in the IPv4 family.
// For cluster types other than STRICT_DNS and LOGICAL_DNS, this setting is
// ignored.
type Cluster_DnsLookupFamily int32

const (
	Cluster_AUTO    Cluster_DnsLookupFamily = 0
	Cluster_V4_ONLY Cluster_DnsLookupFamily = 1
	Cluster_V6_ONLY Cluster_DnsLookupFamily = 2
)

var Cluster_DnsLookupFamily_name = map[int32]string{
	0: "AUTO",
	1: "V4_ONLY",
	2: "V6_ONLY",
}
var Cluster_DnsLookupFamily_value = map[string]int32{
	"AUTO":    0,
	"V4_ONLY": 1,
	"V6_ONLY": 2,
}

func (x Cluster_DnsLookupFamily) String() string {
	return proto.EnumName(Cluster_DnsLookupFamily_name, int32(x))
}
func (Cluster_DnsLookupFamily) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

// The behavior used when no endpoint subset matches the selected route's
// metadata. The options are NO_FALLBACK, ANY_ENDPOINT, or DEFAULT_SUBSET.
// The value defaults to NO_FALLBACK. If NO_FALLBACK is selected, a result
// equivalent to no healthy hosts is reported. If ANY_ENDPOINT is selected,
// any cluster endpoint may be returned (subject to policy, health checks,
// etc). If DEFAULT_SUBSET is selected, load balancing is performed over the
// endpoints matching the values from the default_subset field.
type Cluster_LbSubsetConfig_LbSubsetFallbackPolicy int32

const (
	Cluster_LbSubsetConfig_NO_FALLBACK    Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 0
	Cluster_LbSubsetConfig_ANY_ENDPOINT   Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 1
	Cluster_LbSubsetConfig_DEFAULT_SUBSET Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 2
)

var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name = map[int32]string{
	0: "NO_FALLBACK",
	1: "ANY_ENDPOINT",
	2: "DEFAULT_SUBSET",
}
var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value = map[string]int32{
	"NO_FALLBACK":    0,
	"ANY_ENDPOINT":   1,
	"DEFAULT_SUBSET": 2,
}

func (x Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) String() string {
	return proto.EnumName(Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, int32(x))
}
func (Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 2, 0}
}

// An extensible structure containing the address Envoy should bind to when establishing upstream
// connections.
type UpstreamBindConfig struct {
	// The address Envoy should bind to when establishing upstream connections.
	SourceAddress *envoy_api_v21.Address `protobuf:"bytes,1,opt,name=source_address,json=sourceAddress" json:"source_address,omitempty"`
}

func (m *UpstreamBindConfig) Reset()                    { *m = UpstreamBindConfig{} }
func (m *UpstreamBindConfig) String() string            { return proto.CompactTextString(m) }
func (*UpstreamBindConfig) ProtoMessage()               {}
func (*UpstreamBindConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpstreamBindConfig) GetSourceAddress() *envoy_api_v21.Address {
	if m != nil {
		return m.SourceAddress
	}
	return nil
}

// Circuit breaking settings can be specified individually for each defined
// priority.
type CircuitBreakers struct {
	Thresholds []*CircuitBreakers_Thresholds `protobuf:"bytes,1,rep,name=thresholds" json:"thresholds,omitempty"`
}

func (m *CircuitBreakers) Reset()                    { *m = CircuitBreakers{} }
func (m *CircuitBreakers) String() string            { return proto.CompactTextString(m) }
func (*CircuitBreakers) ProtoMessage()               {}
func (*CircuitBreakers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CircuitBreakers) GetThresholds() []*CircuitBreakers_Thresholds {
	if m != nil {
		return m.Thresholds
	}
	return nil
}

type CircuitBreakers_Thresholds struct {
	Priority envoy_api_v22.RoutingPriority `protobuf:"varint,1,opt,name=priority,enum=envoy.api.v2.RoutingPriority" json:"priority,omitempty"`
	// The maximum number of connections that Envoy will make to the upstream
	// cluster. If not specified, the default is 1024. See the circuit
	// breaking overview for more information.
	MaxConnections *google_protobuf2.UInt32Value `protobuf:"bytes,2,opt,name=max_connections,json=maxConnections" json:"max_connections,omitempty"`
	// The maximum number of pending requests that Envoy will allow to the
	// upstream cluster. If not specified, the default is 1024. See the circuit
	// breaking overview for more information.
	MaxPendingRequests *google_protobuf2.UInt32Value `protobuf:"bytes,3,opt,name=max_pending_requests,json=maxPendingRequests" json:"max_pending_requests,omitempty"`
	// The maximum number of parallel requests that Envoy will make to the
	// upstream cluster. If not specified, the default is 1024. See the circuit
	// breaking overview for more information.
	MaxRequests *google_protobuf2.UInt32Value `protobuf:"bytes,4,opt,name=max_requests,json=maxRequests" json:"max_requests,omitempty"`
	// The maximum number of parallel retries that Envoy will allow to the
	// upstream cluster. If not specified, the default is 3. See the circuit
	// breaking overview for more information.
	MaxRetries *google_protobuf2.UInt32Value `protobuf:"bytes,5,opt,name=max_retries,json=maxRetries" json:"max_retries,omitempty"`
}

func (m *CircuitBreakers_Thresholds) Reset()                    { *m = CircuitBreakers_Thresholds{} }
func (m *CircuitBreakers_Thresholds) String() string            { return proto.CompactTextString(m) }
func (*CircuitBreakers_Thresholds) ProtoMessage()               {}
func (*CircuitBreakers_Thresholds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *CircuitBreakers_Thresholds) GetPriority() envoy_api_v22.RoutingPriority {
	if m != nil {
		return m.Priority
	}
	return envoy_api_v22.RoutingPriority_DEFAULT
}

func (m *CircuitBreakers_Thresholds) GetMaxConnections() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxConnections
	}
	return nil
}

func (m *CircuitBreakers_Thresholds) GetMaxPendingRequests() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxPendingRequests
	}
	return nil
}

func (m *CircuitBreakers_Thresholds) GetMaxRequests() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxRequests
	}
	return nil
}

func (m *CircuitBreakers_Thresholds) GetMaxRetries() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxRetries
	}
	return nil
}

type Cluster struct {
	// Supplies the name of the cluster which must be unique across all clusters.
	// The cluster name is used when emitting statistics. The cluster name can be
	// at most 60 characters long, and must not contain :.
	Name             string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             Cluster_DiscoveryType     `protobuf:"varint,2,opt,name=type,enum=envoy.api.v2.Cluster_DiscoveryType" json:"type,omitempty"`
	EdsClusterConfig *Cluster_EdsClusterConfig `protobuf:"bytes,3,opt,name=eds_cluster_config,json=edsClusterConfig" json:"eds_cluster_config,omitempty"`
	// The timeout for new network connections to hosts in the cluster.
	ConnectTimeout *google_protobuf.Duration `protobuf:"bytes,4,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	// Soft limit on size of the cluster’s connections read and write buffers. If
	// unspecified, an implementation defined default is applied (1MiB).
	PerConnectionBufferLimitBytes *google_protobuf2.UInt32Value `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes" json:"per_connection_buffer_limit_bytes,omitempty"`
	LbPolicy                      Cluster_LbPolicy              `protobuf:"varint,6,opt,name=lb_policy,json=lbPolicy,enum=envoy.api.v2.Cluster_LbPolicy" json:"lb_policy,omitempty"`
	// If the service discovery type is STATIC, STRICT_DNS or LOGICAL_DNS, then
	// hosts is required.
	Hosts []*envoy_api_v21.Address `protobuf:"bytes,7,rep,name=hosts" json:"hosts,omitempty"`
	// Optional active health checking configuration for the cluster. If no
	// configuration is specified no health checking will be done and all cluster
	// members will be considered healthy at all times.
	HealthChecks []*envoy_api_v24.HealthCheck `protobuf:"bytes,8,rep,name=health_checks,json=healthChecks" json:"health_checks,omitempty"`
	// Optional maximum requests for a single upstream connection. This parameter
	// is respected by both the HTTP/1.1 and HTTP/2 connection pool
	// implementations. If not specified, there is no limit. Setting this
	// parameter to 1 will effectively disable keep alive.
	MaxRequestsPerConnection *google_protobuf2.UInt32Value `protobuf:"bytes,9,opt,name=max_requests_per_connection,json=maxRequestsPerConnection" json:"max_requests_per_connection,omitempty"`
	// Optional circuit breaking settings for the cluster.
	CircuitBreakers *CircuitBreakers `protobuf:"bytes,10,opt,name=circuit_breakers,json=circuitBreakers" json:"circuit_breakers,omitempty"`
	// The TLS configuration for connections to the upstream cluster. If no TLS
	// configuration is specified, TLS will not be used for new connections.
	TlsContext *envoy_api_v26.UpstreamTlsContext `protobuf:"bytes,11,opt,name=tls_context,json=tlsContext" json:"tls_context,omitempty"`
	// Types that are valid to be assigned to ProtocolOptions:
	//	*Cluster_TcpProtocolOptions
	//	*Cluster_HttpProtocolOptions
	//	*Cluster_Http2ProtocolOptions
	//	*Cluster_GrpcProtocolOptions
	ProtocolOptions isCluster_ProtocolOptions `protobuf_oneof:"protocol_options"`
	// If the dns refresh rate is specified and the cluster type is either
	// STRICT_DNS, or LOGICAL_DNS, this value is used as the cluster’s dns refresh
	// rate. If this setting is not specified, the value defaults to 5000. For
	// cluster types other than STRICT_DNS and LOGICAL_DNS this setting is
	// ignored.
	DnsRefreshRate  *google_protobuf.Duration `protobuf:"bytes,16,opt,name=dns_refresh_rate,json=dnsRefreshRate" json:"dns_refresh_rate,omitempty"`
	DnsLookupFamily Cluster_DnsLookupFamily   `protobuf:"varint,17,opt,name=dns_lookup_family,json=dnsLookupFamily,enum=envoy.api.v2.Cluster_DnsLookupFamily" json:"dns_lookup_family,omitempty"`
	// If DNS resolvers are specified and the cluster type is either STRICT_DNS,
	// or LOGICAL_DNS, this value is used to specify the cluster’s dns resolvers.
	// If this setting is not specified, the value defaults to the default
	// resolver, which uses /etc/resolv.conf for configuration. For cluster types
	// other than STRICT_DNS and LOGICAL_DNS this setting is ignored.
	DnsResolvers     []*envoy_api_v21.Address  `protobuf:"bytes,18,rep,name=dns_resolvers,json=dnsResolvers" json:"dns_resolvers,omitempty"`
	OutlierDetection *Cluster_OutlierDetection `protobuf:"bytes,19,opt,name=outlier_detection,json=outlierDetection" json:"outlier_detection,omitempty"`
	// The interval for removing stale hosts from a cluster type
	// ORIGINAL_DST.  Hosts are considered stale if they have not been used
	// as upstream destinations during this interval.  New hosts are added
	// to original destination clusters on demand as new connections are
	// redirected to Envoy, causing the number of hosts in the cluster to
	// grow over time.  Hosts that are not stale (they are actively used as
	// destinations) are kept in the cluster, which allows connections to
	// them remain open, saving the latency that would otherwise be spent
	// on opening new connections.  If this setting is not specified, the
	// value defaults to 5000ms. For cluster types other than ORIGINAL_DST
	// this setting is ignored.
	CleanupInterval *google_protobuf.Duration `protobuf:"bytes,20,opt,name=cleanup_interval,json=cleanupInterval" json:"cleanup_interval,omitempty"`
	// Optional configuration used to bind newly established upstream connections.
	// This overrides any bind_config specified in the bootstrap proto.
	// If the addres and port are empty, no bind will be performed.
	UpstreamBindConfig *envoy_api_v21.BindConfig `protobuf:"bytes,21,opt,name=upstream_bind_config,json=upstreamBindConfig" json:"upstream_bind_config,omitempty"`
	LbSubsetConfig     *Cluster_LbSubsetConfig   `protobuf:"bytes,22,opt,name=lb_subset_config,json=lbSubsetConfig" json:"lb_subset_config,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isCluster_ProtocolOptions interface {
	isCluster_ProtocolOptions()
}

type Cluster_TcpProtocolOptions struct {
	TcpProtocolOptions *envoy_api_v25.TcpProtocolOptions `protobuf:"bytes,12,opt,name=tcp_protocol_options,json=tcpProtocolOptions,oneof"`
}
type Cluster_HttpProtocolOptions struct {
	HttpProtocolOptions *envoy_api_v25.Http1ProtocolOptions `protobuf:"bytes,13,opt,name=http_protocol_options,json=httpProtocolOptions,oneof"`
}
type Cluster_Http2ProtocolOptions struct {
	Http2ProtocolOptions *envoy_api_v25.Http2ProtocolOptions `protobuf:"bytes,14,opt,name=http2_protocol_options,json=http2ProtocolOptions,oneof"`
}
type Cluster_GrpcProtocolOptions struct {
	GrpcProtocolOptions *envoy_api_v25.GrpcProtocolOptions `protobuf:"bytes,15,opt,name=grpc_protocol_options,json=grpcProtocolOptions,oneof"`
}

func (*Cluster_TcpProtocolOptions) isCluster_ProtocolOptions()   {}
func (*Cluster_HttpProtocolOptions) isCluster_ProtocolOptions()  {}
func (*Cluster_Http2ProtocolOptions) isCluster_ProtocolOptions() {}
func (*Cluster_GrpcProtocolOptions) isCluster_ProtocolOptions()  {}

func (m *Cluster) GetProtocolOptions() isCluster_ProtocolOptions {
	if m != nil {
		return m.ProtocolOptions
	}
	return nil
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetType() Cluster_DiscoveryType {
	if m != nil {
		return m.Type
	}
	return Cluster_STATIC
}

func (m *Cluster) GetEdsClusterConfig() *Cluster_EdsClusterConfig {
	if m != nil {
		return m.EdsClusterConfig
	}
	return nil
}

func (m *Cluster) GetConnectTimeout() *google_protobuf.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *Cluster) GetPerConnectionBufferLimitBytes() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

func (m *Cluster) GetLbPolicy() Cluster_LbPolicy {
	if m != nil {
		return m.LbPolicy
	}
	return Cluster_ROUND_ROBIN
}

func (m *Cluster) GetHosts() []*envoy_api_v21.Address {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Cluster) GetHealthChecks() []*envoy_api_v24.HealthCheck {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *Cluster) GetMaxRequestsPerConnection() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return nil
}

func (m *Cluster) GetCircuitBreakers() *CircuitBreakers {
	if m != nil {
		return m.CircuitBreakers
	}
	return nil
}

func (m *Cluster) GetTlsContext() *envoy_api_v26.UpstreamTlsContext {
	if m != nil {
		return m.TlsContext
	}
	return nil
}

func (m *Cluster) GetTcpProtocolOptions() *envoy_api_v25.TcpProtocolOptions {
	if x, ok := m.GetProtocolOptions().(*Cluster_TcpProtocolOptions); ok {
		return x.TcpProtocolOptions
	}
	return nil
}

func (m *Cluster) GetHttpProtocolOptions() *envoy_api_v25.Http1ProtocolOptions {
	if x, ok := m.GetProtocolOptions().(*Cluster_HttpProtocolOptions); ok {
		return x.HttpProtocolOptions
	}
	return nil
}

func (m *Cluster) GetHttp2ProtocolOptions() *envoy_api_v25.Http2ProtocolOptions {
	if x, ok := m.GetProtocolOptions().(*Cluster_Http2ProtocolOptions); ok {
		return x.Http2ProtocolOptions
	}
	return nil
}

func (m *Cluster) GetGrpcProtocolOptions() *envoy_api_v25.GrpcProtocolOptions {
	if x, ok := m.GetProtocolOptions().(*Cluster_GrpcProtocolOptions); ok {
		return x.GrpcProtocolOptions
	}
	return nil
}

func (m *Cluster) GetDnsRefreshRate() *google_protobuf.Duration {
	if m != nil {
		return m.DnsRefreshRate
	}
	return nil
}

func (m *Cluster) GetDnsLookupFamily() Cluster_DnsLookupFamily {
	if m != nil {
		return m.DnsLookupFamily
	}
	return Cluster_AUTO
}

func (m *Cluster) GetDnsResolvers() []*envoy_api_v21.Address {
	if m != nil {
		return m.DnsResolvers
	}
	return nil
}

func (m *Cluster) GetOutlierDetection() *Cluster_OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *Cluster) GetCleanupInterval() *google_protobuf.Duration {
	if m != nil {
		return m.CleanupInterval
	}
	return nil
}

func (m *Cluster) GetUpstreamBindConfig() *envoy_api_v21.BindConfig {
	if m != nil {
		return m.UpstreamBindConfig
	}
	return nil
}

func (m *Cluster) GetLbSubsetConfig() *Cluster_LbSubsetConfig {
	if m != nil {
		return m.LbSubsetConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Cluster) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Cluster_OneofMarshaler, _Cluster_OneofUnmarshaler, _Cluster_OneofSizer, []interface{}{
		(*Cluster_TcpProtocolOptions)(nil),
		(*Cluster_HttpProtocolOptions)(nil),
		(*Cluster_Http2ProtocolOptions)(nil),
		(*Cluster_GrpcProtocolOptions)(nil),
	}
}

func _Cluster_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Cluster)
	// protocol_options
	switch x := m.ProtocolOptions.(type) {
	case *Cluster_TcpProtocolOptions:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TcpProtocolOptions); err != nil {
			return err
		}
	case *Cluster_HttpProtocolOptions:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpProtocolOptions); err != nil {
			return err
		}
	case *Cluster_Http2ProtocolOptions:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Http2ProtocolOptions); err != nil {
			return err
		}
	case *Cluster_GrpcProtocolOptions:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GrpcProtocolOptions); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Cluster.ProtocolOptions has unexpected type %T", x)
	}
	return nil
}

func _Cluster_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Cluster)
	switch tag {
	case 12: // protocol_options.tcp_protocol_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(envoy_api_v25.TcpProtocolOptions)
		err := b.DecodeMessage(msg)
		m.ProtocolOptions = &Cluster_TcpProtocolOptions{msg}
		return true, err
	case 13: // protocol_options.http_protocol_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(envoy_api_v25.Http1ProtocolOptions)
		err := b.DecodeMessage(msg)
		m.ProtocolOptions = &Cluster_HttpProtocolOptions{msg}
		return true, err
	case 14: // protocol_options.http2_protocol_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(envoy_api_v25.Http2ProtocolOptions)
		err := b.DecodeMessage(msg)
		m.ProtocolOptions = &Cluster_Http2ProtocolOptions{msg}
		return true, err
	case 15: // protocol_options.grpc_protocol_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(envoy_api_v25.GrpcProtocolOptions)
		err := b.DecodeMessage(msg)
		m.ProtocolOptions = &Cluster_GrpcProtocolOptions{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Cluster_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Cluster)
	// protocol_options
	switch x := m.ProtocolOptions.(type) {
	case *Cluster_TcpProtocolOptions:
		s := proto.Size(x.TcpProtocolOptions)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Cluster_HttpProtocolOptions:
		s := proto.Size(x.HttpProtocolOptions)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Cluster_Http2ProtocolOptions:
		s := proto.Size(x.Http2ProtocolOptions)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Cluster_GrpcProtocolOptions:
		s := proto.Size(x.GrpcProtocolOptions)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Only valid when discovery type is EDS.
type Cluster_EdsClusterConfig struct {
	EdsConfig *envoy_api_v22.ConfigSource `protobuf:"bytes,1,opt,name=eds_config,json=edsConfig" json:"eds_config,omitempty"`
	// Optional alternative to cluster name to present to EDS. This does not
	// have the same restrictions as cluster name, i.e. it may be arbritary
	// length and contain ':'.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *Cluster_EdsClusterConfig) Reset()                    { *m = Cluster_EdsClusterConfig{} }
func (m *Cluster_EdsClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_EdsClusterConfig) ProtoMessage()               {}
func (*Cluster_EdsClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Cluster_EdsClusterConfig) GetEdsConfig() *envoy_api_v22.ConfigSource {
	if m != nil {
		return m.EdsConfig
	}
	return nil
}

func (m *Cluster_EdsClusterConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// If specified, outlier detection will be enabled for this upstream cluster.
type Cluster_OutlierDetection struct {
	// The number of consecutive 5xx responses before a consecutive 5xx ejection
	// occurs. Defaults to 5.
	Consecutive_5Xx *google_protobuf2.UInt32Value `protobuf:"bytes,1,opt,name=consecutive_5xx,json=consecutive5xx" json:"consecutive_5xx,omitempty"`
	// The time interval between ejection analysis sweeps. This can result in
	// both new ejections as well as hosts being returned to service. Defaults
	// to 10000ms or 10s.
	Interval *google_protobuf.Duration `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
	// The base time that a host is ejected for. The real time is equal to the
	// base time multiplied by the number of times the host has been ejected.
	// Defaults to 30000ms or 30s.
	BaseEjectionTime *google_protobuf.Duration `protobuf:"bytes,3,opt,name=base_ejection_time,json=baseEjectionTime" json:"base_ejection_time,omitempty"`
	// The maximum % of an upstream cluster that can be ejected due to outlier
	// detection. Defaults to 10%.
	MaxEjectionPercent *google_protobuf2.UInt32Value `protobuf:"bytes,4,opt,name=max_ejection_percent,json=maxEjectionPercent" json:"max_ejection_percent,omitempty"`
	// The % chance that a host will be actually ejected when an outlier status
	// is detected through consecutive 5xx. This setting can be used to disable
	// ejection or to ramp it up slowly. Defaults to 100.
	EnforcingConsecutive_5Xx *google_protobuf2.UInt32Value `protobuf:"bytes,5,opt,name=enforcing_consecutive_5xx,json=enforcingConsecutive5xx" json:"enforcing_consecutive_5xx,omitempty"`
	// The % chance that a host will be actually ejected when an outlier status
	// is detected through success rate statistics. This setting can be used to
	// disable ejection or to ramp it up slowly. Defaults to 100.
	EnforcingSuccessRate *google_protobuf2.UInt32Value `protobuf:"bytes,6,opt,name=enforcing_success_rate,json=enforcingSuccessRate" json:"enforcing_success_rate,omitempty"`
	// The number of hosts in a cluster that must have enough request volume to
	// detect success rate outliers. If the number of hosts is less than this
	// setting, outlier detection via success rate statistics is not performed
	// for any host in the cluster. Defaults to 5.
	SuccessRateMinimumHosts *google_protobuf2.UInt32Value `protobuf:"bytes,7,opt,name=success_rate_minimum_hosts,json=successRateMinimumHosts" json:"success_rate_minimum_hosts,omitempty"`
	// The minimum number of total requests that must be collected in one
	// interval (as defined by the interval duration above) to include this host
	// in success rate based outlier detection. If the volume is lower than this
	// setting, outlier detection via success rate statistics is not performed
	// for that host. Defaults to 100.
	SuccessRateRequestVolume *google_protobuf2.UInt32Value `protobuf:"bytes,8,opt,name=success_rate_request_volume,json=successRateRequestVolume" json:"success_rate_request_volume,omitempty"`
	// This factor is used to determine the ejection threshold for success rate
	// outlier ejection. The ejection threshold is the difference between the
	// mean success rate, and the product of this factor and the standard
	// deviation of the mean success rate: mean - (stdev *
	// success_rate_stdev_factor). This factor is divided by a thousand to get a
	// double. That is, if the desired factor is 1.9, the runtime value should
	// be 1900. Defaults to 1900.
	SuccessRateStdevFactor *google_protobuf2.UInt32Value `protobuf:"bytes,9,opt,name=success_rate_stdev_factor,json=successRateStdevFactor" json:"success_rate_stdev_factor,omitempty"`
}

func (m *Cluster_OutlierDetection) Reset()                    { *m = Cluster_OutlierDetection{} }
func (m *Cluster_OutlierDetection) String() string            { return proto.CompactTextString(m) }
func (*Cluster_OutlierDetection) ProtoMessage()               {}
func (*Cluster_OutlierDetection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Cluster_OutlierDetection) GetConsecutive_5Xx() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.Consecutive_5Xx
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetInterval() *google_protobuf.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetBaseEjectionTime() *google_protobuf.Duration {
	if m != nil {
		return m.BaseEjectionTime
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetMaxEjectionPercent() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.MaxEjectionPercent
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetEnforcingConsecutive_5Xx() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.EnforcingConsecutive_5Xx
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetEnforcingSuccessRate() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.EnforcingSuccessRate
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetSuccessRateMinimumHosts() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.SuccessRateMinimumHosts
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetSuccessRateRequestVolume() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.SuccessRateRequestVolume
	}
	return nil
}

func (m *Cluster_OutlierDetection) GetSuccessRateStdevFactor() *google_protobuf2.UInt32Value {
	if m != nil {
		return m.SuccessRateStdevFactor
	}
	return nil
}

// Optionally divide the endpoints in this cluster into subsets defined by
// endpoint metadata and selected by route and weighted cluster metadata.
type Cluster_LbSubsetConfig struct {
	FallbackPolicy Cluster_LbSubsetConfig_LbSubsetFallbackPolicy `protobuf:"varint,1,opt,name=fallback_policy,json=fallbackPolicy,enum=envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy" json:"fallback_policy,omitempty"`
	// Specifies the default subset of endpoints used during fallback if
	// fallback_policy is DEFAULT_SUBSET. Each field in default_subset is
	// compared to the matching LbEndpoint.Metadata under the "envoy.lb"
	// namespace. It is valid for no hosts to match, in which case the behavior
	// is the same as a fallback_policy of NO_FALLBACK.
	DefaultSubset   *google_protobuf1.Struct                   `protobuf:"bytes,2,opt,name=default_subset,json=defaultSubset" json:"default_subset,omitempty"`
	SubsetSelectors []*Cluster_LbSubsetConfig_LbSubsetSelector `protobuf:"bytes,3,rep,name=subset_selectors,json=subsetSelectors" json:"subset_selectors,omitempty"`
}

func (m *Cluster_LbSubsetConfig) Reset()                    { *m = Cluster_LbSubsetConfig{} }
func (m *Cluster_LbSubsetConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig) ProtoMessage()               {}
func (*Cluster_LbSubsetConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *Cluster_LbSubsetConfig) GetFallbackPolicy() Cluster_LbSubsetConfig_LbSubsetFallbackPolicy {
	if m != nil {
		return m.FallbackPolicy
	}
	return Cluster_LbSubsetConfig_NO_FALLBACK
}

func (m *Cluster_LbSubsetConfig) GetDefaultSubset() *google_protobuf1.Struct {
	if m != nil {
		return m.DefaultSubset
	}
	return nil
}

func (m *Cluster_LbSubsetConfig) GetSubsetSelectors() []*Cluster_LbSubsetConfig_LbSubsetSelector {
	if m != nil {
		return m.SubsetSelectors
	}
	return nil
}

// Specifications for subsets. For each entry, LbEndpoint.Metadata's
// "envoy.lb" namespace is traversed and a subset is created for each unique
// combination of key and value. For example:
// { "subset_selectors": [
//     { "keys": [ "version" ] },
//     { "keys": [ "stage", "hardware_type" ] }
// ]}
// A subset is matched when the metadata from the selected route and
// weighted cluster contains the same keys and values as the subset's
// metadata. The same host may appear in multiple subsets.
type Cluster_LbSubsetConfig_LbSubsetSelector struct {
	Keys []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) Reset() {
	*m = Cluster_LbSubsetConfig_LbSubsetSelector{}
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) String() string { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig_LbSubsetSelector) ProtoMessage()    {}
func (*Cluster_LbSubsetConfig_LbSubsetSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 2, 0}
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*UpstreamBindConfig)(nil), "envoy.api.v2.UpstreamBindConfig")
	proto.RegisterType((*CircuitBreakers)(nil), "envoy.api.v2.CircuitBreakers")
	proto.RegisterType((*CircuitBreakers_Thresholds)(nil), "envoy.api.v2.CircuitBreakers.Thresholds")
	proto.RegisterType((*Cluster)(nil), "envoy.api.v2.Cluster")
	proto.RegisterType((*Cluster_EdsClusterConfig)(nil), "envoy.api.v2.Cluster.EdsClusterConfig")
	proto.RegisterType((*Cluster_OutlierDetection)(nil), "envoy.api.v2.Cluster.OutlierDetection")
	proto.RegisterType((*Cluster_LbSubsetConfig)(nil), "envoy.api.v2.Cluster.LbSubsetConfig")
	proto.RegisterType((*Cluster_LbSubsetConfig_LbSubsetSelector)(nil), "envoy.api.v2.Cluster.LbSubsetConfig.LbSubsetSelector")
	proto.RegisterEnum("envoy.api.v2.Cluster_DiscoveryType", Cluster_DiscoveryType_name, Cluster_DiscoveryType_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbPolicy", Cluster_LbPolicy_name, Cluster_LbPolicy_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_DnsLookupFamily", Cluster_DnsLookupFamily_name, Cluster_DnsLookupFamily_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy", Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value)
}

func init() { proto.RegisterFile("api/cds.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x98, 0xdd, 0x72, 0xe3, 0x48,
	0x15, 0xc7, 0x63, 0x27, 0x33, 0x93, 0x1c, 0xc7, 0xb6, 0xd2, 0x93, 0xc9, 0x68, 0x3c, 0x3b, 0xcb,
	0x8e, 0x81, 0xad, 0x29, 0xa8, 0xf2, 0x80, 0x97, 0x40, 0xed, 0x2c, 0x2c, 0xe5, 0xaf, 0x24, 0x06,
	0xaf, 0x9d, 0x6d, 0x29, 0x33, 0x3b, 0x6c, 0x15, 0x8d, 0x2c, 0xb5, 0x6d, 0x11, 0x59, 0x12, 0xea,
	0x96, 0xb1, 0x6f, 0x79, 0x03, 0x8a, 0xd7, 0xe1, 0x25, 0x28, 0xee, 0xb9, 0xa2, 0x0a, 0x1e, 0x83,
	0xea, 0x56, 0xdb, 0xb1, 0xe4, 0x64, 0x62, 0xaa, 0xf6, 0x4e, 0x7d, 0xfa, 0xfc, 0x7f, 0x6a, 0x1d,
	0xe9, 0x7c, 0xd8, 0x50, 0xb4, 0x42, 0xf7, 0xb5, 0xed, 0xb0, 0x5a, 0x18, 0x05, 0x3c, 0x40, 0x87,
	0xd4, 0x9f, 0x05, 0x8b, 0x9a, 0x15, 0xba, 0xb5, 0x59, 0xbd, 0x72, 0x24, 0x36, 0x2d, 0xc7, 0x89,
	0x28, 0x53, 0x0e, 0x95, 0x92, 0x30, 0x0d, 0x2d, 0x46, 0xd5, 0xfa, 0xb1, 0x58, 0x3b, 0x2e, 0xb3,
	0x83, 0x19, 0x8d, 0x16, 0xca, 0x78, 0x22, 0x8c, 0x13, 0x6a, 0x79, 0x7c, 0x42, 0xec, 0x09, 0xb5,
	0xaf, 0x95, 0x1d, 0x09, 0xbb, 0xbc, 0xb4, 0x03, 0x4f, 0xd9, 0xe4, 0x01, 0xd8, 0xf2, 0x00, 0x95,
	0x8f, 0xc6, 0x41, 0x30, 0xf6, 0xe8, 0x6b, 0x79, 0x67, 0xdf, 0x0f, 0xb8, 0xc5, 0xdd, 0xc0, 0x5f,
	0xee, 0x7e, 0xac, 0x76, 0xe5, 0x6a, 0x18, 0x8f, 0x5e, 0x3b, 0x71, 0x24, 0x1d, 0x32, 0xea, 0xd5,
	0x3e, 0xe3, 0x51, 0x6c, 0xf3, 0xbb, 0xd4, 0x7f, 0x8e, 0xac, 0x30, 0xa4, 0x91, 0xa2, 0x57, 0x31,
	0xa0, 0xab, 0x90, 0xf1, 0x88, 0x5a, 0xd3, 0xa6, 0xeb, 0x3b, 0xad, 0xc0, 0x1f, 0xb9, 0x63, 0xf4,
	0x4b, 0x28, 0xb1, 0x20, 0x8e, 0x6c, 0x4a, 0x54, 0x24, 0xf4, 0xdc, 0x27, 0xb9, 0x57, 0x85, 0xfa,
	0x93, 0xda, 0x7a, 0xac, 0x6a, 0x8d, 0x64, 0x13, 0x17, 0x13, 0x67, 0xb5, 0xac, 0xfe, 0x7d, 0x17,
	0xca, 0x2d, 0x37, 0xb2, 0x63, 0x97, 0x37, 0x23, 0x6a, 0x5d, 0xd3, 0x88, 0xa1, 0x0b, 0x00, 0x3e,
	0x89, 0x28, 0x9b, 0x04, 0x9e, 0x23, 0x68, 0xbb, 0xaf, 0x0a, 0xf5, 0x57, 0x69, 0x5a, 0x46, 0x52,
	0x33, 0x57, 0xfe, 0x78, 0x4d, 0x5b, 0xf9, 0x57, 0x1e, 0xe0, 0x66, 0x0b, 0x7d, 0x0e, 0xfb, 0x61,
	0xe4, 0x06, 0x91, 0xcb, 0x17, 0xf2, 0x90, 0xa5, 0xfa, 0x8b, 0x34, 0x16, 0x07, 0x31, 0x77, 0xfd,
	0xf1, 0xa5, 0x72, 0xc2, 0x2b, 0x77, 0xd4, 0x81, 0xf2, 0xd4, 0x9a, 0x13, 0x3b, 0xf0, 0x7d, 0x6a,
	0xcb, 0x90, 0xeb, 0x79, 0xf9, 0x98, 0x1f, 0xd5, 0x92, 0xa8, 0xd5, 0x96, 0x51, 0xab, 0x5d, 0x75,
	0x7d, 0xfe, 0x59, 0xfd, 0xad, 0xe5, 0xc5, 0x14, 0x97, 0xa6, 0xd6, 0xbc, 0x75, 0xa3, 0x41, 0x7d,
	0x38, 0x16, 0x98, 0x90, 0xfa, 0x8e, 0xeb, 0x8f, 0x49, 0x44, 0xff, 0x14, 0x53, 0xc6, 0x99, 0xbe,
	0xbb, 0x05, 0x0b, 0x4d, 0xad, 0xf9, 0x65, 0x22, 0xc4, 0x4a, 0x87, 0x7e, 0x0d, 0x87, 0x82, 0xb7,
	0xe2, 0xec, 0x6d, 0xc1, 0x29, 0x4c, 0xad, 0xf9, 0x0a, 0xf0, 0x2b, 0x28, 0x24, 0x00, 0x1e, 0xb9,
	0x94, 0xe9, 0x0f, 0xb6, 0xd0, 0x83, 0xd4, 0x4b, 0xff, 0xea, 0x3f, 0x74, 0x78, 0xd4, 0xf2, 0x62,
	0xc6, 0x69, 0x84, 0x10, 0xec, 0xf9, 0xd6, 0x94, 0xca, 0xc8, 0x1e, 0x60, 0x79, 0x8d, 0x7e, 0x01,
	0x7b, 0x7c, 0x11, 0x52, 0x19, 0xab, 0x52, 0xfd, 0xfb, 0x99, 0x97, 0x98, 0x08, 0x6b, 0xed, 0x65,
	0x7a, 0x98, 0x8b, 0x90, 0x62, 0x29, 0x40, 0x26, 0x20, 0xea, 0x30, 0x62, 0x27, 0x2e, 0x22, 0xee,
	0x23, 0x77, 0xac, 0xc2, 0xf4, 0xe9, 0xed, 0x98, 0x8e, 0xc3, 0xd4, 0x65, 0xf2, 0x65, 0x62, 0x8d,
	0x66, 0x2c, 0xa8, 0x09, 0x65, 0xf5, 0x06, 0x09, 0x77, 0xa7, 0x34, 0x88, 0xb9, 0x8a, 0xd8, 0xb3,
	0x8d, 0x27, 0x6e, 0xab, 0xcc, 0xc1, 0x25, 0xa5, 0x30, 0x13, 0x01, 0x1a, 0xc1, 0xcb, 0x30, 0x39,
	0x91, 0x7a, 0xab, 0x64, 0x18, 0x8f, 0x46, 0x34, 0x22, 0x9e, 0x3b, 0x75, 0x39, 0x19, 0x2e, 0xf8,
	0x96, 0x71, 0x7c, 0x11, 0xca, 0x73, 0x29, 0x4a, 0x53, 0x42, 0x7a, 0x82, 0xd1, 0x14, 0x08, 0xf4,
	0x05, 0x1c, 0x78, 0x43, 0x12, 0x06, 0x9e, 0x6b, 0x2f, 0xf4, 0x87, 0x32, 0x7e, 0x1f, 0xdf, 0xfe,
	0xe0, 0xbd, 0xe1, 0xa5, 0xf4, 0xc2, 0xfb, 0x9e, 0xba, 0x42, 0x3f, 0x86, 0x07, 0x93, 0x40, 0x7c,
	0x10, 0x8f, 0x64, 0xf6, 0xdc, 0x91, 0x8b, 0x89, 0x0f, 0xfa, 0x12, 0x8a, 0xeb, 0xc5, 0x88, 0xe9,
	0xfb, 0x52, 0xf4, 0x2c, 0x2d, 0xba, 0x90, 0x2e, 0x2d, 0xe1, 0x81, 0x0f, 0x27, 0x37, 0x0b, 0x86,
	0xbe, 0x85, 0xe7, 0xeb, 0x1f, 0x21, 0x49, 0x87, 0x47, 0x3f, 0xd8, 0x22, 0x16, 0xfa, 0xda, 0x37,
	0x79, 0xb9, 0x1e, 0x16, 0x74, 0x01, 0x9a, 0x9d, 0x24, 0x3b, 0x19, 0xaa, 0x6c, 0xd7, 0x41, 0x12,
	0x5f, 0x7c, 0xb0, 0x24, 0xe0, 0xb2, 0x9d, 0x29, 0x2b, 0x0d, 0x28, 0x70, 0x8f, 0x89, 0x93, 0x71,
	0x3a, 0xe7, 0x7a, 0x41, 0x42, 0x3e, 0x49, 0x43, 0x96, 0xf5, 0xcd, 0xf4, 0x58, 0x2b, 0xf1, 0xc3,
	0xc0, 0x57, 0xd7, 0xc8, 0x84, 0x63, 0x6e, 0x87, 0x64, 0x59, 0xa2, 0x49, 0x10, 0x26, 0xa5, 0xe0,
	0xf0, 0x36, 0x96, 0x69, 0x87, 0x97, 0xca, 0x71, 0x90, 0xf8, 0x5d, 0xec, 0x60, 0xc4, 0x37, 0xac,
	0xe8, 0x1b, 0x78, 0x32, 0xe1, 0xfc, 0x16, 0x6c, 0x51, 0x62, 0xab, 0x99, 0xf7, 0xc0, 0x79, 0xf8,
	0xd3, 0x4d, 0xf0, 0x63, 0x81, 0xc8, 0x92, 0x7f, 0x07, 0x27, 0xc2, 0x5c, 0xdf, 0x44, 0x97, 0xee,
	0x42, 0xd7, 0x37, 0xd1, 0xc7, 0x93, 0x5b, 0xec, 0xe8, 0x1d, 0x3c, 0x19, 0x47, 0xa1, 0xbd, 0x89,
	0x2e, 0x4b, 0xf4, 0xcb, 0x34, 0xfa, 0x3c, 0x0a, 0xed, 0x5b, 0x0e, 0x3d, 0xde, 0x34, 0xa3, 0x16,
	0x68, 0x8e, 0xcf, 0x48, 0x44, 0x47, 0xa2, 0x70, 0x93, 0xc8, 0xe2, 0x54, 0xd7, 0xee, 0xcd, 0x52,
	0xc7, 0x67, 0x38, 0x51, 0x60, 0x8b, 0x53, 0xf4, 0x35, 0x1c, 0x09, 0x88, 0x17, 0x04, 0xd7, 0x71,
	0x48, 0x46, 0xd6, 0xd4, 0xf5, 0x16, 0xfa, 0x91, 0xcc, 0xa2, 0x1f, 0xde, 0x51, 0x85, 0x7c, 0xd6,
	0x93, 0xde, 0x67, 0xd2, 0x19, 0x97, 0x9d, 0xb4, 0x01, 0xbd, 0x81, 0x62, 0x72, 0x2e, 0x16, 0x78,
	0x33, 0xf1, 0x19, 0xa2, 0x0f, 0xe5, 0xd6, 0xa1, 0x3c, 0x90, 0x72, 0x45, 0x06, 0x1c, 0x05, 0x31,
	0xf7, 0x5c, 0x1a, 0x11, 0x87, 0x72, 0x95, 0x18, 0x8f, 0x3f, 0x54, 0xcd, 0x06, 0x89, 0x7b, 0x7b,
	0xe9, 0x8d, 0xb5, 0x20, 0x63, 0x41, 0x6d, 0xd0, 0x6c, 0x8f, 0x5a, 0x7e, 0x1c, 0x12, 0xd7, 0xe7,
	0x34, 0x9a, 0x59, 0x9e, 0x7e, 0x7c, 0x5f, 0xa0, 0xca, 0x4a, 0xd2, 0x55, 0x0a, 0xf4, 0x1b, 0x38,
	0x8e, 0xd5, 0x57, 0x4f, 0x86, 0xae, 0xef, 0x2c, 0x6b, 0xed, 0x13, 0x49, 0xd2, 0xd3, 0xa7, 0xbb,
	0xe9, 0xfb, 0x18, 0xc5, 0x9b, 0xb3, 0x40, 0x1f, 0x34, 0x6f, 0x48, 0x58, 0x3c, 0x64, 0x94, 0x2f,
	0x39, 0x27, 0x92, 0xf3, 0x83, 0xbb, 0x4a, 0x97, 0x21, 0x9d, 0x15, 0xb3, 0xe4, 0xa5, 0xd6, 0x95,
	0x10, 0xb4, 0x6c, 0x55, 0x47, 0x9f, 0x03, 0xc8, 0xce, 0x90, 0xd0, 0x93, 0x59, 0xa3, 0x92, 0xa1,
	0xcb, 0x3d, 0x43, 0x0e, 0x1a, 0xf8, 0x40, 0x74, 0x81, 0x44, 0xfa, 0x12, 0x0e, 0x19, 0x8d, 0x66,
	0xae, 0x4d, 0x89, 0xec, 0x54, 0x79, 0xd9, 0xa9, 0x0a, 0xca, 0xd6, 0xb7, 0xa6, 0xb4, 0xf2, 0xdf,
	0x07, 0xa0, 0x65, 0x43, 0x2f, 0x9a, 0xbf, 0x1d, 0xf8, 0x8c, 0xda, 0x31, 0x77, 0x67, 0x94, 0x9c,
	0xce, 0xe7, 0xea, 0xbe, 0xf7, 0x34, 0xff, 0x35, 0xd1, 0xe9, 0x7c, 0x8e, 0x4e, 0x61, 0x7f, 0xf5,
	0x9e, 0xf2, 0xf7, 0xbd, 0xa7, 0x95, 0x2b, 0x3a, 0x07, 0x24, 0x06, 0x4a, 0x42, 0xff, 0xa8, 0xfa,
	0x8d, 0x68, 0x5d, 0xaa, 0x15, 0x7e, 0x00, 0xa0, 0x09, 0x51, 0x47, 0x69, 0x44, 0xf3, 0x5a, 0x0e,
	0x1f, 0x2b, 0x4e, 0x48, 0x23, 0x9b, 0xfa, 0x7c, 0xab, 0xa1, 0x41, 0x0c, 0x1f, 0x4b, 0xd8, 0x65,
	0xa2, 0x43, 0xdf, 0xc0, 0x33, 0xea, 0x8f, 0x82, 0xc8, 0x16, 0xa3, 0x4c, 0x36, 0x40, 0xdb, 0x74,
	0xc0, 0xa7, 0x2b, 0x79, 0x2b, 0x1d, 0x29, 0x0c, 0x27, 0x37, 0x64, 0x16, 0xdb, 0x36, 0x65, 0x2c,
	0x29, 0x04, 0x0f, 0xb7, 0xc0, 0x1e, 0xaf, 0xb4, 0x46, 0x22, 0x95, 0x15, 0xe1, 0x3d, 0x54, 0xd6,
	0x49, 0x64, 0xea, 0xfa, 0xee, 0x34, 0x9e, 0x92, 0x65, 0x9f, 0xdc, 0xe2, 0xb8, 0xec, 0x06, 0xf7,
	0x55, 0xa2, 0xbe, 0x90, 0x0d, 0xf4, 0x5b, 0x78, 0x9e, 0x42, 0xab, 0x4e, 0x48, 0x66, 0x81, 0x17,
	0x4f, 0xa9, 0xbe, 0xbf, 0x4d, 0x03, 0x5c, 0x63, 0xab, 0x46, 0xf8, 0x56, 0xaa, 0xd1, 0x3b, 0x78,
	0x96, 0x82, 0x33, 0xee, 0xd0, 0x19, 0x19, 0x59, 0x36, 0x0f, 0xa2, 0xad, 0x7a, 0xeb, 0xc9, 0x1a,
	0xda, 0x10, 0xe2, 0x33, 0xa9, 0xad, 0xfc, 0x75, 0x17, 0x4a, 0xe9, 0xfc, 0x43, 0x0e, 0x94, 0x47,
	0x96, 0xe7, 0x0d, 0x2d, 0xfb, 0x7a, 0x39, 0x79, 0x24, 0x73, 0xf2, 0x17, 0xdb, 0xa4, 0xef, 0x6a,
	0x79, 0xa6, 0x18, 0x6a, 0x2c, 0x29, 0x8d, 0x52, 0x6b, 0xf4, 0x25, 0x94, 0x1c, 0x3a, 0xb2, 0x62,
	0x8f, 0xab, 0x52, 0xa1, 0xb2, 0xe1, 0xe9, 0xc6, 0x63, 0x18, 0xf2, 0xe7, 0x09, 0x2e, 0x2a, 0xf7,
	0x84, 0x8e, 0xfe, 0x00, 0x9a, 0x2a, 0x31, 0x8c, 0x7a, 0x54, 0x3c, 0x8b, 0x18, 0xa0, 0x45, 0x2d,
	0x3e, 0xfd, 0xbf, 0x8e, 0x69, 0x28, 0x35, 0x2e, 0xb3, 0xd4, 0x9a, 0x55, 0x3e, 0x05, 0x2d, 0xeb,
	0x24, 0xc6, 0xdb, 0x6b, 0xba, 0x48, 0x7e, 0x8f, 0x1c, 0x60, 0x79, 0x5d, 0x1d, 0xc0, 0xc9, 0xed,
	0xcf, 0x8c, 0xca, 0x50, 0xe8, 0x0f, 0xc8, 0x59, 0xa3, 0xd7, 0x6b, 0x36, 0x5a, 0xbf, 0xd5, 0x76,
	0x90, 0x06, 0x87, 0x8d, 0xfe, 0x7b, 0xd2, 0xe9, 0xb7, 0x2f, 0x07, 0xdd, 0xbe, 0xa9, 0xe5, 0x10,
	0x82, 0x52, 0xbb, 0x73, 0xd6, 0xb8, 0xea, 0x99, 0xc4, 0xb8, 0x6a, 0x1a, 0x1d, 0x53, 0xcb, 0x57,
	0xdf, 0x41, 0x31, 0x35, 0x0d, 0x23, 0x80, 0x87, 0x86, 0xd9, 0x30, 0xbb, 0x2d, 0x6d, 0x07, 0x95,
	0x00, 0x0c, 0x13, 0x77, 0x5b, 0x26, 0x69, 0xf7, 0x0d, 0x2d, 0x27, 0xee, 0xd1, 0x1b, 0x9c, 0x77,
	0x5b, 0x8d, 0x9e, 0x34, 0xe4, 0xd1, 0x23, 0xd8, 0xed, 0xb4, 0x0d, 0x6d, 0x57, 0xdc, 0x6c, 0x80,
	0xbb, 0xe7, 0xdd, 0xbe, 0xd8, 0x32, 0x4c, 0x6d, 0xaf, 0xfa, 0x7b, 0xd8, 0x5f, 0x8e, 0x89, 0x42,
	0x87, 0x07, 0x57, 0xfd, 0x36, 0xc1, 0x83, 0x66, 0xb7, 0xaf, 0xed, 0xa0, 0x23, 0x28, 0xf6, 0x3a,
	0x0d, 0xc3, 0x24, 0xb8, 0xf3, 0xf5, 0x55, 0xc7, 0x10, 0x87, 0x2b, 0xc2, 0x01, 0xee, 0xf6, 0xcf,
	0xc9, 0x45, 0xc3, 0xb8, 0xd0, 0xf2, 0xe2, 0x18, 0xb8, 0xd1, 0x6f, 0x0f, 0xbe, 0xd2, 0x76, 0xd1,
	0x63, 0x28, 0xaf, 0xc3, 0x49, 0xaf, 0xa9, 0xed, 0x55, 0x4f, 0xa1, 0x9c, 0x69, 0xa0, 0x68, 0x1f,
	0xf6, 0x1a, 0x57, 0xe6, 0x40, 0xdb, 0x41, 0x05, 0x78, 0xf4, 0xf6, 0x67, 0x64, 0xd0, 0xef, 0xbd,
	0xd7, 0x72, 0x72, 0xf1, 0xf3, 0x64, 0x91, 0x6f, 0x22, 0xd0, 0xb2, 0xf3, 0x43, 0xfd, 0x3f, 0x39,
	0x78, 0xaa, 0xde, 0xdc, 0x2a, 0x16, 0x46, 0x52, 0xa2, 0xd1, 0x3b, 0x28, 0x19, 0xb2, 0xe9, 0x28,
	0x07, 0x86, 0x32, 0x33, 0xf1, 0x4a, 0xa1, 0x92, 0xa8, 0xf2, 0xbd, 0x3b, 0xf7, 0x59, 0x28, 0x8a,
	0x4e, 0x75, 0xe7, 0x55, 0xee, 0x27, 0x39, 0xc4, 0xa0, 0x78, 0x46, 0xb9, 0x3d, 0xf9, 0xee, 0xb8,
	0x2f, 0xff, 0xf2, 0xcf, 0x7f, 0xff, 0x2d, 0xff, 0xbc, 0x7a, 0xf2, 0x7a, 0x56, 0xbf, 0xf9, 0x07,
	0xe0, 0x8d, 0xfa, 0x45, 0xc3, 0xde, 0xe4, 0x7e, 0x34, 0x7c, 0x28, 0x9f, 0xfd, 0xb3, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x0e, 0x7e, 0xc1, 0x25, 0x65, 0x10, 0x00, 0x00,
}
