#!/bin/bash
cat <<EOF
// Code generated by wordlist_process.sh.
// DO NOT EDIT!

package mixer

// GlobalList of known words
func GlobalList() []string {
	tmp := make([]string, len(globalList))
	copy(tmp, globalList)
	return tmp
}

var (
	globalList = []string{
EOF

cat - |\
  sed '/^#/d' |\
  sed '/^\s*$/d' |\
  sed 's/^- \(.*\)$/\t\t"\1",/'

cat <<EOF
	}
)
EOF
