# Change this and ../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy-debug:0b521718b2cb00c43a016bd5c8b9c5f2205f8469
ADD pilot-agent /usr/local/bin/pilot-agent
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
