# Change this and ../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy:2816746cc96f27ae2fb88b076f3ac1a8eb34b75b
ADD pilot-agent /usr/local/bin/pilot-agent
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
