# Change this and ../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy-debug:e630beb83d3be0bf0d46657ab2deb472e4b6eee1
ADD pilot-agent /usr/local/bin/pilot-agent
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
