# Change this and ../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy:4547a0567d16e245984f900542cbb745a55eda09
ADD pilot-agent /usr/local/bin/pilot-agent
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
