# Change this and ../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy:adf0dc47bb397b8d5d994f37e51642281c5520e3
ADD pilot-agent /usr/local/bin/pilot-agent
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
